#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    opt.load('compiler_cxx')
    opt.load('java')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('java')
    conf.check_jni_headers()
    conf.check_cxx(header_name='malloc.h', features='cxx cxxprogram', mandatory=False)
    conf.check_cxx(header_name='limits.h', features='cxx cxxprogram', mandatory=False)
    conf.env.INCLUDES = [ '.', '..']
    conf.env.CXXFLAGS = ['-Wall', '-O3', '-fPIC' ]
    conf.env.CORE_SRC = ['core/*.cpp']
    conf.env.JNI_SRC = ['jni/*.cpp']

def build(bld):
    bld.objects( source = bld.path.ant_glob(bld.env.CORE_SRC), target = 'core' )
    bld.shlib( source = bld.path.ant_glob(bld.env.JNI_SRC), uselib = 'JAVA', use = 'core', target = 'zchaffmincost' )

   
