/**
 * 
 */
package kodkod.multiobjective.statistics;

public enum StatKey {
	REGULAR_SAT_CALL,
	REGULAR_UNSAT_CALL,

	REGULAR_SAT_TIME,
	REGULAR_UNSAT_TIME,
	
	REGULAR_SAT_TIME_TRANSLATION,
	REGULAR_UNSAT_TIME_TRANSLATION,
	
	REGULAR_SAT_TIME_SOLVING,
	REGULAR_UNSAT_TIME_SOLVING,
	
	MAGNIFIER_SAT_CALL,
	MAGNIFIER_UNSAT_CALL,
	MAGNIFIER_TIME,
	
	OPTIMAL_SOLNS,
	OPTIMAL_METRIC_POINTS,
	
	BEGIN_TIME,
	END_TIME,
	DURATION, 
	
	CLAUSES,
	VARIABLES,
}